### ISSUE TITLE
[Feature][Bug] Do not have enabling both Ethernet + Wifi

### ISSUE THREAD

**Issue by manhnguyen2301** [khieuvm/InternetSwitch#1]
I think you need add "Enable Both" and rename "Disable Wifi" to "Enable Ethernet". I will pay for you. Hurry up

**Comment by khieuvm** [comment]
Thank you for your comment.
I released a new version of this feature. Please help me enjoy it!

**Comment by manhnguyen2301** [comment]
Thank you. Money is transferred to you. Please check the bank account.
